force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>Holds the referral records in it.</description>
    <label>Referral</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>referral Email</description>
    <inlineHelpText>referral Email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Expressed_interest__c.field-meta.xml
<CustomField>
    <fullName>Expressed_interest__c</fullName>
    <description>product interest</description>
    <label>Expressed interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial Advisory</fullName>
            </value>
            <value>
                <fullName>Home Lending</fullName>
            </value>
            <value>
                <fullName>Premier banking</fullName>
            </value>
            <value>
                <fullName>Private Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>referral Phone</description>
    <inlineHelpText>referral Phone</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk load</fullName>
            </value>
            <value>
                <fullName>From any CRM system</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed-Lost</fullName>
            </value>
            <value>
                <fullName>Closed-Won</fullName>
            </value>
            <value>
                <fullName>Followup</fullName>
            </value>
            <value>
                <fullName>Identify</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferralController.cls
public with sharing class ReferralController {
    @AuraEnabled
    public static List<Referral__C> getReferrals(){
        List<Referral__C> refList=new List<Referral__c>();
        try{          
        
        refList=[SELECT Id, FirstName__c, Last_Name__c, Email__c, Phone__c, Expressed_interest__c, Stage__c, Source__c  FROM Referral__c Limit 10];
        }
        catch(Exception ex){
            throw ex;
        }
        return refList;
    }

}