force-app/main/default/objects/Banker__c/Banker__c.object-meta.xml
<CustomObject>
    <description>holds the banker details</description>
    <label>Banker</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Banker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bankers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Banker__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Dynamics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Banker__c/fields/Baker_Id__c.field-meta.xml
<CustomField>
    <fullName>Baker_Id__c</fullName>
    <description>banker identification number</description>
    <externalId>true</externalId>
    <label>Baker Id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Banker__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Branch code</description>
    <inlineHelpText>branch code</inlineHelpText>
    <label>Branch Code</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Banker__c/fields/capacity__c.field-meta.xml
<CustomField>
    <fullName>capacity__c</fullName>
    <defaultValue>5</defaultValue>
    <label>capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Banker__c/fields/Deals_With__c.field-meta.xml
<CustomField>
    <fullName>Deals_With__c</fullName>
    <label>Deals With</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fin Products</fullName>
            </value>
            <value>
                <fullName>Service Goods</fullName>
            </value>
            <value>
                <fullName>Electronic Management</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Banker__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>Holds the referral records in it.</description>
    <label>Referral</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>Banker__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RefAgentIdentification.cls
public class RefAgentIdentification {
    public static AgentWrapper findAgentDetails(list<string> lstInterests, string PrevAgentID){
        List<AgentWrapper> agntWrapLst = new List<AgentWrapper>();
         for(Banker__c bnk:[SELECT Id, Name, Deals_With__c, capacity__c,Application_Type__c, Branch_Code__c, 
                            Baker_Id__c,User__c,(select id from Referrals__r) 
                            FROM Banker__c where Deals_With__c IN: lstInterests AND Baker_Id__c !=: PrevAgentID]){
            AgentWrapper bnkobj = new AgentWrapper(bnk.Baker_Id__c,bnk.User__c,Integer.valueOf(bnk.capacity__c - bnk.Referrals__r.size()),bnk.Id,bnk.Application_Type__c);
            agntWrapLst.add(bnkobj);
        }
        agntWrapLst.sort();
        return agntWrapLst[0];
    }
}