force-app/main/default/objects/Banker__c/Banker__c.object-meta.xml
<CustomObject>
    <description>holds the banker details</description>
    <label>Banker</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Banker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bankers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Banker__c/fields/Baker_Id__c.field-meta.xml
<CustomField>
    <fullName>Baker_Id__c</fullName>
    <description>banker identification number</description>
    <externalId>true</externalId>
    <label>Baker Id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Banker__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Branch code</description>
    <inlineHelpText>branch code</inlineHelpText>
    <label>Branch Code</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Banker__c/fields/capacity__c.field-meta.xml
<CustomField>
    <fullName>capacity__c</fullName>
    <defaultValue>5</defaultValue>
    <label>capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Banker__c/fields/Deals_With__c.field-meta.xml
<CustomField>
    <fullName>Deals_With__c</fullName>
    <label>Deals With</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fin Products</fullName>
            </value>
            <value>
                <fullName>Service Goods</fullName>
            </value>
            <value>
                <fullName>Electronic Management</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Banker__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>Holds the referral records in it.</description>
    <label>Referral</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>Banker__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Expressed_interest__c.field-meta.xml
<CustomField>
    <fullName>Expressed_interest__c</fullName>
    <description>product interest</description>
    <label>Expressed interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial Advisory</fullName>
            </value>
            <value>
                <fullName>Home Lending</fullName>
            </value>
            <value>
                <fullName>Premier banking</fullName>
            </value>
            <value>
                <fullName>Private Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/recordAssignment.cls
public class recordAssignment {
    public static void assignRecords(List<Referral__c> refRecords){
        // Listing all expressed interests
        List<String> expInterestedList = new List<String>();
        for(Referral__c eachrec:refRecords){
            expInterestedList.add(eachRec.Expressed_interest__c);
        }
        
        //Preparing all bankers who are most available
        Map<string,List<bankerWrpper>> bankerMap = new Map<string,List<bankerWrpper>>();
        for(Banker__c bnk:[SELECT Id, Name, Deals_With__c, capacity__c, Branch_Code__c, Baker_Id__c,User__c,(select id from Referrals__r) FROM Banker__c where Deals_With__c IN: expInterestedList]){
            bankerWrpper bnkobj = new bankerWrpper(bnk.Baker_Id__c,bnk.User__c,Integer.valueOf(bnk.capacity__c - bnk.Referrals__r.size()),bnk.Id);
            if(!bankerMap.containsKey(bnk.Deals_With__c)){
                bankerMap.put(bnk.Deals_With__c,new List<bankerWrpper>());
            }
            bankerMap.get(bnk.Deals_With__c).add(bnkobj);
        }
        
        // Assigning records to banker object
        for(Referral__c eachrec:refRecords){
            List<bankerWrpper> bankerList = bankerMap.get(eachrec.Expressed_interest__c);
            if(! bankerList.isEmpty()){
                bankerList.sort();
                system.debug('bankerList : '+bankerList);
                eachrec.Banker__c = bankerList[0].recId;
                bankerList[0].remainingCapacity = bankerList[0].remainingCapacity - 1;
                if(String.isNotBlank(bankerList[0].User) && String.isNotEmpty(bankerList[0].User)){
                     eachrec.OwnerId = bankerList[0].User;
                }
                bankerMap.put(eachrec.Expressed_interest__c,bankerList);
            }
        }
        
    }
    
    public class bankerWrpper implements Comparable {
        Public string recId;
        Public string BankerId;
        Public string User;
        public integer remainingCapacity;
        public bankerWrpper(string BankerId,string User,integer remainingCapacity,string recId){
            this.BankerId = BankerId;
            this.User = User;
            this.remainingCapacity = remainingCapacity;
            this.recId = recId;
        }
        public Integer compareTo(Object compareTo) {
            recordAssignment.bankerWrpper otherWrapper = (recordAssignment.bankerWrpper)compareTo;
            Integer returnValue = 0;
            if (this.remainingCapacity < otherWrapper.remainingCapacity) {
                returnValue = 1;
            } else if (this.remainingCapacity > otherWrapper.remainingCapacity) {
                returnValue = -1;
            } 
            return returnValue;
        }
    }
}