force-app/main/default/objects/LeadEvent__e/LeadEvent__e.object-meta.xml
<CustomObject>
    <description>Main event for capturing data within the system</description>
    <label>LeadEvent</label>
    <pluralLabel>LeadEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/LeadEvent__e/fields/Current_Agent_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Agent_ID__c</fullName>
    <label>Current Agent ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Current_App_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_App_ID__c</fullName>
    <description>Application ID of the current calculated destination system</description>
    <label>Current App ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <label>Customer ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Message_Payload__c.field-meta.xml
<CustomField>
    <fullName>Message_Payload__c</fullName>
    <label>Message Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Previous_Agent_ID__c.field-meta.xml
<CustomField>
    <fullName>Previous_Agent_ID__c</fullName>
    <label>Previous Agent ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Previous_App_ID__c.field-meta.xml
<CustomField>
    <fullName>Previous_App_ID__c</fullName>
    <description>Application ID of the previous calculated destination system</description>
    <label>Previous App ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/SLA_In_Hours__c.field-meta.xml
<CustomField>
    <fullName>SLA_In_Hours__c</fullName>
    <defaultValue>48</defaultValue>
    <label>SLA In Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <label>Status</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadEvent__e/fields/System_Trail__c.field-meta.xml
<CustomField>
    <fullName>System_Trail__c</fullName>
    <description>trail of systems visited</description>
    <label>System Trail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvaluateForLead.cls
//Class for executing the logic

public class EvaluateForLead {
    public EvaluateForLead(){}
    
    public string evaluateAgent(list<string> lstInterests, string PrevAgentID){
        string evaluatedAgentId = '';
        return evaluatedAgentId;
    }
    
    public string evaluateCustomer(list<string> lstMessagePayload){
        string cutomerId = '';
        return cutomerId;
    }
    
    public LeadEvent__e createLeadEvent(string custId, String agentId, LeadEvent__e IncomingEvent){
        LeadEvent__e returnEvent = new LeadEvent__e();
        returnEvent.Current_Agent_ID__c = !string.isBlank(agentId)?agentId:null;
        returnEvent.Current_App_ID__c = IncomingEvent.Current_App_ID__c;
        returnEvent.Customer_ID__c = !string.isBlank(custId)?custId:null;
        returnEvent.Message_Payload__c =  IncomingEvent.Message_Payload__c;
        returnEvent.Previous_Agent_ID__c = IncomingEvent.Previous_Agent_ID__c;
        returnEvent.Previous_App_ID__c = IncomingEvent.Previous_App_ID__c;
        returnEvent.SLA_In_Hours__c = IncomingEvent.SLA_In_Hours__c;
        returnEvent.Status__c =  IncomingEvent.Status__c;
        returnEvent.Sub_Status__c = IncomingEvent.Sub_Status__c;
        returnEvent.System_Trail__c = IncomingEvent.System_Trail__c;
        returnEvent.TimeStamp__c = IncomingEvent.TimeStamp__c;  
        return returnEvent;
    }
}